### PR TITLE
Automatically create amd64 and arm64 Docker images

### PR DESCRIPTION
**Pull request by SShah7433**
args: operating system (OS) and architecture (ARCH)

### CODE REVIEW

**Comment by SShah7433** [comment]
Reopening with complete changes

**Comment by SShah7433** [comment]
@eko - As a note, docker hub credentials will have to be added to the repo for this to work.

**Comment by SShah7433** [comment]
Would help provide remediation for https://github.com/eko/pihole-exporter/issues/13

**Comment by eko** [comment]
Hi @SShah7433,

Great, thanks, I added the `DOCKER_USERNAME` and `DOCKER_PASSWORD` secrets to the repository but it continues to fail when trying to push the image on the docker hub:

```bash
Successfully built 4584a8bc87f9
Successfully tagged ekofr/pihole-exporter:amd64
Successfully tagged ekofr/pihole-exporter:sha-0bcc3d8
Pushing image [ekofr/pihole-exporter:amd64 ekofr/pihole-exporter:sha-0bcc3d8]
The push refers to repository [docker.io/ekofr/pihole-exporter]
19f790e656cf: Preparing
0f990a9408a4: Preparing
denied: requested access to the resource is denied
Error: exit status 1
exit status 1
```

**Comment by SShah7433** [comment]
@eko - Oddly enough, it completed successfully on my repo. Before I start dgging further, could you double check the credentials?

**Comment by eko** [comment]
Hi @SShah7433, I think I just understood why, when reading the settings page:
> Secrets are not passed to workflows that are triggered by a pull request from a fork

I will merge this PR now to see if it's work on master branch ;)

Thank you!

**Comment by eko** [comment]
Great, image has been built and pushed successfully: https://hub.docker.com/layers/ekofr/pihole-exporter/amd64/images/sha256-f5ac0ce43622ce7be4489a8d93c6bdb0ca9b17c314784e3a440468a2c3a5d39b?context=repo

**Pull request merged**
